modLoader="javafml"  # mod加载器,必填
loaderVersion="[47,)"  # mod加载器版本,必填
license="All rights reserved"  # 许可证,必填

[[mods]]  # mod信息,必填
modId="delicate_little_garbage"  # modid,必填
version="0.0.9-bata"  # mod版本,必填
displayName="DLG"  # mod显示名称,必填
logoFile="logo.png"  # mod图标,选填
authors="yueyingiop"  # mod作者,选填
description='''
    修改了一些原版的机制
    可以通过配置文件启用哪些功能
'''  # mod描述,必填

[[dependencies.delicate_little_garbage]]  # mod依赖,选填
    modId="forge"  # 依赖的modid,必填
    mandatory=true  # 是否必须,必填
    versionRange="[47.4.0,)"  # 依赖的版本范围,必填
    ordering="NONE"  # 排序,选填
    side="BOTH"  # 端,选填

[[dependencies.delicate_little_garbage]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH" 
    
[[dependencies.delicate_little_garbage]]
   modId="kubejs"
   mandatory=false
   versionRange="[2001.6.5-build.16,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.delicate_little_garbage]]
    modId="appleskin"
    mandatory=false
    versionRange="[mc1.20.1-2.5.1,)"
    ordering="NONE"
    side="BOTH"